//=--------------------------------------------------------------------------=
// Dispids.H
//=--------------------------------------------------------------------------=
// Copyright  1995  Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
// PARTICULAR PURPOSE.
//=--------------------------------------------------------------------------=
//
// dispids for use in an automation or control object.
//
#ifndef _DISPIDS_H_

//=--------------------------------------------------------------------------=
// for the ielnk control
// properties & methods
//

#define DISPID_HLINK		101
#define DISPID_LOCATION		102
#define	DISPID_FORWARD		103
#define DISPID_BACK			104
#define	DISPID_GO			105
#define	DISPID_TARGETFRAME	106
#define DISPID_FLAGS		107
#define DISPID_MODE			108

// events
//


#define _DISPIDS_H_
#endif // _DISPIDS_H_
