//=--------------------------------------------------------------------------=
// Guids.H
//=--------------------------------------------------------------------------=
// Copyright  1995  Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
// PARTICULAR PURPOSE.
//=--------------------------------------------------------------------------=
//
// guids that we define locally
//
#ifndef _GUIDS_H_

// for each property page this server will have, put the guid definition for it
// here so that it gets defined ...
//
DEFINE_GUID(CLSID_iemimGeneralPage, 0x11bf24c0, 0xa295, 0x11cf, 0xa3, 0xa9, 0x00, 0xa0, 0xc9, 0x03, 0x49, 0x20);


#define _GUIDS_H_
#endif // _GUIDS_H_


