#=--------------------------------------------------------------------------=
# Makefile
#=--------------------------------------------------------------------------=
# Copyright 1995-1996 Microsoft Corporation.  All Rights Reserved.
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
# PARTICULAR PURPOSE.
#=--------------------------------------------------------------------------=
#
# Builds the ObjVw Control
#

USE_BASECTL = 1

Proj = ObjVw

# pull in the master SDK makefile that Defines all of the macros
#  and all of the build rules

!include <INetSDK.Mak>

all: $(ObjDir)\$(Proj).Ocx Register

# itemize all of the required Object files

Objs=$(ObjDir)\Guids.Obj \
     $(ObjDir)\objvw.Obj \
     $(ObjDir)\objvwctl.Obj  \
     $(ObjDir)\treeui.Obj    \
     $(ObjDir)\wintree.Obj \
     $(ObjDir)\appsink.Obj \
     $(ObjDir)\cathelp.Obj \
     $(ObjDir)\evtsink.Obj \
     $(ObjDir)\$(Proj).Res

# special case the odl file since the output header has a special name

$(Proj)Int.h: $(Proj).Odl
  mktyplib /DWIN32 -I..\Include /h $(Proj)Int.h /tlb $(Proj).Tlb $(Proj).Odl

# and finally, just Define the dependencies

$(ObjDir)\$(Proj).Ocx: $(Objs)

$(ObjDir)\Guids.Obj: $(@B).Cpp $(Proj)Int.h
