//=--------------------------------------------------------------------------=
// Resource.H
//=--------------------------------------------------------------------------=
// Copyright 1995-1996 Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
// PARTICULAR PURPOSE.
//=--------------------------------------------------------------------------=
//
// resource IDs.
//
#ifndef _RESOURCE_H_

#define RESID_TOOLBOX_BITMAP          1

//=--------------------------------------------------------------------------=
// Strings
//

//=--------------------------------------------------------------------------=
// Dialog Stuff
//
#define _RESOURCE_H_
#endif // _RESOURCE_H_
