//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Progress.rc
//
#define IDD_DIALOG1                     101
#define IDC_DISPLAY                     1001
#define IDC_PROGRESS                    1002
#define IDC_EDIT                        1011
#define IDC_PROGRESSBAR                 1013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
