Proj = HttpAuth

# These are "extra" libs beyond the standard set that inetsdk.mak will
#  append to the libs set

libs=wininet.lib

# pull in the master SDK makefile that defines all of the macros
#  and all of the build rules

console=1

!include <inetsdk.mak>

all: $(ObjDir)\$(Proj).Exe

# itemize all of the required Object files

Objs=   $(ObjDir)\HttpAuth.Obj    \

Includes =

All: $(ObjDir)\$(Proj).Exe

$(ObjDir)\$(Proj).Exe : $(Objs)
