!ifdef clean
makeopts = clean=1
!endif # clean

!ifdef nodebug
makeopts = $(makeopts) nodebug=1
!endif

# If sample is installed, cd into that directory and recursively start nmake.

all:
!IF EXIST (HTTPDump)
 cd HTTPDump
 @$(MAKE) -nologo /$(MAKEFLAGS) $(makeopts)
 cd ..
!ENDIF # exist (HTTPDump)

!IF EXIST (FtpJr)
 cd FtpJr
 @$(MAKE) -nologo /$(MAKEFLAGS) $(makeopts)
 cd ..
!ENDIF # exist (FtpJr)

!IF EXIST (HTTPAuth)
 cd HTTPAuth
 @$(MAKE) -nologo /$(MAKEFLAGS) $(makeopts)
 cd ..
!ENDIF # exist (HTTPAuth)


Clean:
    @nmake -nologo /$(MAKEFLAGS) $(makeopts) clean=1
