//=------------------------------------------------------------------------=
// StdAfx.h
//=------------------------------------------------------------------------=
// Copyright 1992-1996 Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//=--------------------------------------------------------------------------=
//
// include file for standard system include files,
//  or project specific include files that are used frequently, but
//		are changed infrequently

// #define VC_EXTRALEAN

#include <afxwin.h>
#include <afxext.h>
#include <afxole.h>
